title: Agostina Calabrese
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="https://twitter.com/agostina_cal">View My Twitter Profile</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/agostina-calabrese-65b61bbb/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://scholar.google.it/citations?user=ao9qyhwAAAAJ&hl=it&oi=ao">View My Scholar Profile</a> 
  <br><br>
  <a href="{{ site.data.social-media.twitter.href }}{{ site.data.social-media.twitter.id }}" title="Email me">Click here to send me an email!</a>
  
theme: jekyll-theme-minimal
