title: Agostina Calabrese
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <a href="https://twitter.com/agostina_cal">View My Twitter Profile</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/agostina-calabrese-65b61bbb/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
